name: commec-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  # Runtime Python dependencies
  - biopython
  - numpy
  - pandas
  - pytaxonkit
  - pyyaml
  # Runtime non-Python dependencies
  - bedtools
  - blast
  - emboss
  - diamond>=2.1
  - hmmer
  - infernal
  - parallel
  - perl-list-moreutils
  - taxonkit
  - plotly
  - yaml
  - mako
  # Development dependencies
  - pip
  - pytest
  - matplotlib
  - pip:
      - -e .
